### ISSUE TITLE
Send on_ready message to the server the bot is currently in

### ISSUE THREAD

**Issue by qchen59** [qchen59/ScheduleBot#2]
From ScheduleBot created by [ConnorS1110](https://github.com/ConnorS1110): lyonva/ScheduleBot#45  

The bot currently always tries to send the on_ready message to the ScheduleBot discord server and needs to be generalized to work for any server.

**Comment by hughman98** [comment]
Fixed. Just needed to change the line which fetches the channels the bot should send the welcome message to to "channels = bot.get_all_channels()", and then sending the welcome message to all text channels the bot is listening to, instead of specifying a specific text channel.
